### ISSUE TITLE
thank you. Fantastic!

### ISSUE THREAD

**Issue by mediabuff** [walbourn/directx-sdk-legacy-samples#3]

**Comment by mediabuff** [comment]
Is there a possibility of moving all directx samples - current and new - use winrt::com_ptr or wil::com_ptr ?

**Comment by walbourn** [comment]
The samples on **directx-sdk-legacy-samples** are basically the same source code that shipped in the legacy DirectX SDK. Those samples didn't make use of any COM smartpointer and generally used the ``SAFE_RELEASE`` macro style. These were written back in the VS .NET 2003 / VS 2005 timeframe.

For **directx-sdk-samples** and my various GitHub libraries (DirectXTex, DirectXTK, DirectXMesh, etc.) I've used ``WRL::ComPtr``. The main value of this COM smartpointer is:

* It's included in the Windows 8.0 SDK, Windows 8.1 SDK, and Windows 10 SDK.
* It's included in the Xbox One XDK
* It works for UWP apps, Xbox One games, and WIn32 desktop for Windows Vista or later.

The ATL CComPtr is older, but actually is not as ubiquitous. The ATL component is optional with modern Visual Studio, so it's not there by default. Back in the VS 2012 days, ATL wasn't in the Express SKUs.

The only real down-side of ``WRL::ComPtr`` is it is conflated with Windows Runtime so some people think it won't work on Window 7 desktop, and the slightly older C++ style.

Requiring C++/WinRT is not an option because the current generation GDK no longer uses Windows Runtime API design.

The WIL option is problematic because it's not included in any of these platform SDKs.

I hate the idea of having to create *another*  smart-pointer, but something truly stand-alone is needed for my usage cases.

**Comment by mediabuff** [comment]
thanks for for your detailed response.

>> something truly stand-alone is needed for my usage cases.
You may consider: https://github.com/AlexBAV/moderncom
